import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { SiteLayout, PageHeader } from "@/components/site-layout";
import { Button } from "@/components/ui/button";
import { ToolCrossSell } from "@/components/tool-cross-sell";
import { buildSeoMeta } from "@/lib/seo";
import { trackEvent } from "@/lib/analytics";
import {
  ShieldCheck,
  FileText,
  Download,
  CheckCircle2,
  Lock,
  Building2,
  GraduationCap,
  Heart,
  Users,
  Copy,
  Check,
} from "lucide-react";

export const Route = createFileRoute("/governance")({
  head: () => ({
    ...buildSeoMeta({
      title: "AI Governance, Ethics & Policy Starter Kit — Melanated In Tech",
      description:
        "Downloadable AI acceptable use policy templates, data privacy guidelines, vendor risk frameworks, and ethical AI deployment checklists for businesses, nonprofits, and higher ed.",
      url: "/governance",
    }),
  }),
  component: GovernanceKit,
});

interface PolicyTemplate {
  id: string;
  title: string;
  targetAudience: string;
  category: string;
  description: string;
  preview: string;
  fullMarkdown: string;
}

const TEMPLATES: PolicyTemplate[] = [
  {
    id: "acceptable_use",
    title: "Organizational AI Acceptable Use Policy (AUP)",
    targetAudience: "Small Businesses, IT Departments, Tech Teams",
    category: "Corporate Governance",
    description: "Defines permissible AI tool usage, data privacy standards, and zero-data-retention compliance for staff.",
    preview: "1. PURPOSE: Establish rules for utilizing generative AI and automated agents while protecting client PII and IP...",
    fullMarkdown: `# Organizational AI Acceptable Use Policy (AUP)

## 1. Purpose & Scope
This policy governs the acceptable use of Generative AI tools, LLM APIs, and autonomous AI Agents by employees, contractors, and representatives of [ORGANIZATION NAME].

## 2. Approved AI Tool Directory
- **Tier 1 (Approved)**: Enterprise AI tools with zero-data-retention agreements (e.g. OpenAI Enterprise, Claude Team).
- **Tier 2 (Prohibited)**: Public, non-logged AI tools where input data is trained on public models.

## 3. Data Protection & Confidentiality Rules
- **Prohibited Data**: Staff shall NEVER input personally identifiable information (PII), credit card numbers, passwords, or confidential customer records into unapproved public AI tools.
- **Sanitization**: All text inputs must be sanitized or processed using approved internal Prompt Guard proxies.

## 4. Human-in-the-Loop Verification
- Any external document, customer communication, or financial calculation generated by AI must undergo human verification prior to publishing.

## 5. Compliance & Audit
- Failure to comply with this policy may result in revoked AI tool access and disciplinary review.`,
  },
  {
    id: "nonprofit_ethics",
    title: "Nonprofit & Community Ethical AI Framework",
    targetAudience: "Nonprofits, Foundations, Community Organizers",
    category: "Community & Equity",
    description: "Ensures AI automation respects community trust, prevents algorithmic bias, and maintains authentic human relationships.",
    preview: "1. ETHICAL COMMITMENT: We deploy AI to amplify community impact while preserving authentic human ministry and connection...",
    fullMarkdown: `# Nonprofit & Community Ethical AI Framework

## 1. Ethical Commitment
We deploy AI technology to extend our mission, streamline donor stewardship, and automate administrative tasks—never to replace authentic human compassion.

## 2. Core Pillars of Ethical AI
1. **Equity & Anti-Bias**: AI outputs must be regularly audited to prevent algorithmic bias or misrepresentation of marginalized communities.
2. **Transparency**: Beneficiaries and donors must be informed when interacting with automated communications.
3. **Data Sovereignty**: Community member stories and personal counseling records are strictly excluded from AI training sets.

## 3. Community Oversight Committee
- An annual audit shall review AI usage across donor communications, scholarship processing, and community intake.`,
  },
  {
    id: "ministry_ai_guidelines",
    title: "Faith & Ministry AI Deployment Guidelines",
    targetAudience: "Churches, Ministries, Faith-Based Organizations",
    category: "Ministry Governance",
    description: "Balanced guidelines for adopting AI in sermon transcript processing, volunteer coordination, and media outreach.",
    preview: "1. STATEMENT OF FAITH & TECH: Technology serves as a tool for stewardship and outreach, anchored in integrity and truth...",
    fullMarkdown: `# Faith & Ministry AI Deployment Guidelines

## 1. Purpose
To guide pastoral staff, media teams, and ministry leaders in responsibly stewarding AI technology for administrative efficiency and global outreach.

## 2. Permissible Ministry Use Cases
- ✅ **Approved**: Summarizing sermon transcripts for newsletters, generating social media graphics, scheduling volunteer rotas.
- ❌ **Prohibited**: Using AI to generate pastoral counseling advice or substituting AI for personal spiritual care.

## 3. Truth & Attribution
- All media assets and teaching materials produced with AI assistance must align strictly with organizational theological standards and truth.`,
  },
];

export function GovernanceKit() {
  const [selectedId, setSelectedId] = useState<string>("acceptable_use");
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const activeTemplate = TEMPLATES.find((t) => t.id === selectedId) || TEMPLATES[0];

  const handleCopy = (template: PolicyTemplate) => {
    navigator.clipboard.writeText(template.fullMarkdown);
    setCopiedId(template.id);
    trackEvent("tool_export", { tool: "governance_kit", template: template.id });
    setTimeout(() => setCopiedId(null), 2000);
  };

  return (
    <SiteLayout>
      <PageHeader
        eyebrow="Governance & Enablement Hub"
        title="AI Governance, Ethics & Policy Starter Kit"
        description="Download ready-to-use policy templates, acceptable use agreements, and ethical AI deployment frameworks tailored for businesses, nonprofits, and ministries."
      />

      <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
        <div className="grid gap-8 lg:grid-cols-12">
          {/* Template Sidebar */}
          <div className="space-y-4 lg:col-span-5">
            <p className="text-xs font-semibold uppercase tracking-wider text-primary">
              Available Policy Frameworks
            </p>

            {TEMPLATES.map((t) => {
              const isSelected = t.id === selectedId;
              return (
                <div
                  key={t.id}
                  onClick={() => setSelectedId(t.id)}
                  className={`cursor-pointer rounded-2xl border p-5 transition-all ${
                    isSelected
                      ? "border-primary bg-primary/10 ring-1 ring-primary"
                      : "border-border/70 bg-card hover:border-primary/50"
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span className="rounded-full border border-border bg-background px-2.5 py-0.5 text-[10px] font-bold text-muted-foreground">
                      {t.category}
                    </span>
                    <ShieldCheck className="h-4 w-4 text-primary" />
                  </div>
                  <h4 className="mt-2 font-display text-sm font-bold text-foreground">{t.title}</h4>
                  <p className="mt-1 text-xs text-muted-foreground">{t.description}</p>
                </div>
              );
            })}
          </div>

          {/* Template Document Reader */}
          <div className="space-y-6 lg:col-span-7">
            <div className="rounded-2xl border border-border bg-card p-6 shadow-sm">
              <div className="flex items-center justify-between border-b border-border pb-4">
                <div>
                  <h3 className="font-display text-base font-bold">{activeTemplate.title}</h3>
                  <p className="text-xs text-muted-foreground">Target: {activeTemplate.targetAudience}</p>
                </div>

                <Button
                  onClick={() => handleCopy(activeTemplate)}
                  className="gap-2 bg-primary text-xs font-bold"
                >
                  {copiedId === activeTemplate.id ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                  {copiedId === activeTemplate.id ? "Copied Markdown!" : "Copy Full Policy"}
                </Button>
              </div>

              <div className="mt-4">
                <pre className="max-h-[450px] overflow-y-auto rounded-xl border border-border bg-background p-5 font-mono text-xs text-foreground leading-relaxed whitespace-pre-wrap">
                  {activeTemplate.fullMarkdown}
                </pre>
              </div>
            </div>
          </div>
        </div>

        <ToolCrossSell currentToolSlug="governance" />
      </section>
    </SiteLayout>
  );
}
