import { createFileRoute } from "@tanstack/react-router";
import { SiteLayout, PageHeader } from "@/components/site-layout";
import { buildSeoMeta } from "@/lib/seo";

export const Route = createFileRoute("/terms")({
  head: () => ({
    ...buildSeoMeta({
      title: "Terms of Service — Melanated In Tech",
      description:
        "Read the Terms of Service for using the Melanated In Tech platform, tools, and community.",
      url: "/terms",
    }),
  }),
  component: TermsOfService,
});

function TermsOfService() {
  return (
    <SiteLayout>
      <PageHeader
        eyebrow="Legal"
        title="Terms of Service."
        description="Last updated: June 30, 2026. Please read these terms carefully before accessing or using our platform, tools, or community."
      />

      <section className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
        <div className="prose prose-slate dark:prose-invert max-w-none">
          <p>
            Welcome to Melanated In Tech! These Terms of Service (&ldquo;Terms&rdquo;) govern your
            access to and use of the website, tools, products, and community forums provided by
            Melanated In Tech (&ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us&rdquo;). By
            accessing our services, you agree to be bound by these Terms.
          </p>

          <h2>1. Acceptable Use of Services</h2>
          <p>
            You agree to use our platform and interactive prompt tools only for lawful purposes. You
            must not utilize our prompt builders or sandboxes to generate content that:
          </p>
          <ul>
            <li>Is defamatory, obscene, harassing, threatening, or otherwise hateful.</li>
            <li>
              Infringes on the intellectual property, copyright, or trademark rights of others.
            </li>
            <li>Contains viruses, malware, or any other destructive software.</li>
            <li>
              Attempts to exploit, scrape, or circumvent security limits on our AI chat interfaces
              or API endpoints.
            </li>
          </ul>

          <h2>2. User Accounts</h2>
          <p>
            To access certain features (such as saving custom prompts to the database or commenting
            in the community), you must create an account. You are responsible for safeguarding your
            credentials and for all activities that occur under your account. You agree to provide
            accurate and complete registration info.
          </p>

          <h2>3. Intellectual Property Rights</h2>
          <ul>
            <li>
              <strong>Our Content:</strong> The design, layout, assets, software, logos, and
              materials on the platform are owned by Melanated In Tech and protected by copyright
              laws.
            </li>
            <li>
              <strong>Your Contributions:</strong> You retain ownership of the prompts, text, files,
              and comments you create. By posting public content in the Community feed, you grant us
              a worldwide, non-exclusive license to display, distribute, and archive your content
              for community operations.
            </li>
          </ul>

          <h2>4. Payment and Digital Deliverables</h2>
          <p>
            Certain digital products, templates, and agent templates require payment. All
            transactions are billed via Stripe. Unless otherwise noted, all sales of digital
            products are final and non-refundable due to the instant nature of digital delivery.
          </p>

          <h2>5. Disclaimers and Limitation of Liability</h2>
          <p>
            Our services and interactive AI tools are provided &ldquo;as is&rdquo; without
            warranties of any kind. We do not guarantee that the outputs generated by free AI models
            in the Playground will be accurate, complete, or suitable for your business needs.
          </p>
          <p>
            To the maximum extent permitted by law, Melanated In Tech shall not be liable for any
            direct, indirect, incidental, or consequential damages resulting from your use of or
            inability to use our services.
          </p>

          <h2>6. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your account or restrict your access to our
            tools/forums at any time, with or without notice, if we believe you have violated these
            Terms or engaged in harmful activity.
          </p>

          <h2>7. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of the
            jurisdiction in which Melanated In Tech operates, without regard to conflict of law
            principles.
          </p>

          <h2>8. Updates to Terms</h2>
          <p>
            We may revise these Terms from time to time. The most current version will always be
            posted here. By continuing to access the platform after updates become effective, you
            agree to be bound by the revised Terms.
          </p>
        </div>
      </section>
    </SiteLayout>
  );
}
