/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge.$slug'
import { Route as CommunityIdRouteImport } from './routes/community.$id'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthorsSlugRouteImport } from './routes/authors.$slug'
import { Route as AgentsSlugRouteImport } from './routes/agents.$slug'
import { Route as AuthenticatedSubmitAgentRouteImport } from './routes/_authenticated/submit-agent'
import { Route as AuthenticatedSubmissionsRouteImport } from './routes/_authenticated/submissions'
import { Route as AuthenticatedInterestsRouteImport } from './routes/_authenticated/interests'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedSubmissionsIndexRouteImport } from './routes/_authenticated/submissions.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedSubmissionsIdRouteImport } from './routes/_authenticated/submissions.$id'
import { Route as AuthenticatedAdminCatalogRouteImport } from './routes/_authenticated/admin.catalog'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityRoute,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KnowledgeRoute,
} as any)
const CommunityIdRoute = CommunityIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CommunityRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsSlugRoute = AuthorsSlugRouteImport.update({
  id: '/authors/$slug',
  path: '/authors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSlugRoute = AgentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AgentsRoute,
} as any)
const AuthenticatedSubmitAgentRoute =
  AuthenticatedSubmitAgentRouteImport.update({
    id: '/submit-agent',
    path: '/submit-agent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubmissionsRoute =
  AuthenticatedSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterestsRoute = AuthenticatedInterestsRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubmissionsIndexRoute =
  AuthenticatedSubmissionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSubmissionsRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSubmissionsIdRoute =
  AuthenticatedSubmissionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSubmissionsRoute,
  } as any)
const AuthenticatedAdminCatalogRoute =
  AuthenticatedAdminCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRouteWithChildren
  '/contact': typeof ContactRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/interests': typeof AuthenticatedInterestsRoute
  '/submissions': typeof AuthenticatedSubmissionsRouteWithChildren
  '/submit-agent': typeof AuthenticatedSubmitAgentRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/community/$id': typeof CommunityIdRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/agents/': typeof AgentsIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/submissions/$id': typeof AuthenticatedSubmissionsIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/submissions/': typeof AuthenticatedSubmissionsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/interests': typeof AuthenticatedInterestsRoute
  '/submit-agent': typeof AuthenticatedSubmitAgentRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/community/$id': typeof CommunityIdRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/agents': typeof AgentsIndexRoute
  '/community': typeof CommunityIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/submissions/$id': typeof AuthenticatedSubmissionsIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/submissions': typeof AuthenticatedSubmissionsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRouteWithChildren
  '/contact': typeof ContactRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/interests': typeof AuthenticatedInterestsRoute
  '/_authenticated/submissions': typeof AuthenticatedSubmissionsRouteWithChildren
  '/_authenticated/submit-agent': typeof AuthenticatedSubmitAgentRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/community/$id': typeof CommunityIdRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/agents/': typeof AgentsIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/_authenticated/submissions/$id': typeof AuthenticatedSubmissionsIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/submissions/': typeof AuthenticatedSubmissionsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/auth'
    | '/community'
    | '/contact'
    | '/knowledge'
    | '/products'
    | '/search'
    | '/services'
    | '/sitemap.xml'
    | '/account'
    | '/admin'
    | '/interests'
    | '/submissions'
    | '/submit-agent'
    | '/agents/$slug'
    | '/authors/$slug'
    | '/checkout/return'
    | '/community/$id'
    | '/knowledge/$slug'
    | '/products/$slug'
    | '/agents/'
    | '/community/'
    | '/knowledge/'
    | '/products/'
    | '/admin/analytics'
    | '/admin/catalog'
    | '/submissions/$id'
    | '/admin/'
    | '/submissions/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/search'
    | '/services'
    | '/sitemap.xml'
    | '/account'
    | '/interests'
    | '/submit-agent'
    | '/agents/$slug'
    | '/authors/$slug'
    | '/checkout/return'
    | '/community/$id'
    | '/knowledge/$slug'
    | '/products/$slug'
    | '/agents'
    | '/community'
    | '/knowledge'
    | '/products'
    | '/admin/analytics'
    | '/admin/catalog'
    | '/submissions/$id'
    | '/admin'
    | '/submissions'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/agents'
    | '/auth'
    | '/community'
    | '/contact'
    | '/knowledge'
    | '/products'
    | '/search'
    | '/services'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/interests'
    | '/_authenticated/submissions'
    | '/_authenticated/submit-agent'
    | '/agents/$slug'
    | '/authors/$slug'
    | '/checkout/return'
    | '/community/$id'
    | '/knowledge/$slug'
    | '/products/$slug'
    | '/agents/'
    | '/community/'
    | '/knowledge/'
    | '/products/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/catalog'
    | '/_authenticated/submissions/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/submissions/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  ContactRoute: typeof ContactRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthorsSlugRoute: typeof AuthorsSlugRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/community/': {
      id: '/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/community/$id': {
      id: '/community/$id'
      path: '/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof CommunityIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$slug': {
      id: '/authors/$slug'
      path: '/authors/$slug'
      fullPath: '/authors/$slug'
      preLoaderRoute: typeof AuthorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$slug': {
      id: '/agents/$slug'
      path: '/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AgentsSlugRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/_authenticated/submit-agent': {
      id: '/_authenticated/submit-agent'
      path: '/submit-agent'
      fullPath: '/submit-agent'
      preLoaderRoute: typeof AuthenticatedSubmitAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions': {
      id: '/_authenticated/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthenticatedSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interests': {
      id: '/_authenticated/interests'
      path: '/interests'
      fullPath: '/interests'
      preLoaderRoute: typeof AuthenticatedInterestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions/': {
      id: '/_authenticated/submissions/'
      path: '/'
      fullPath: '/submissions/'
      preLoaderRoute: typeof AuthenticatedSubmissionsIndexRouteImport
      parentRoute: typeof AuthenticatedSubmissionsRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/submissions/$id': {
      id: '/_authenticated/submissions/$id'
      path: '/$id'
      fullPath: '/submissions/$id'
      preLoaderRoute: typeof AuthenticatedSubmissionsIdRouteImport
      parentRoute: typeof AuthenticatedSubmissionsRoute
    }
    '/_authenticated/admin/catalog': {
      id: '/_authenticated/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AuthenticatedAdminCatalogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminCatalogRoute: typeof AuthenticatedAdminCatalogRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminCatalogRoute: AuthenticatedAdminCatalogRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSubmissionsRouteChildren {
  AuthenticatedSubmissionsIdRoute: typeof AuthenticatedSubmissionsIdRoute
  AuthenticatedSubmissionsIndexRoute: typeof AuthenticatedSubmissionsIndexRoute
}

const AuthenticatedSubmissionsRouteChildren: AuthenticatedSubmissionsRouteChildren =
  {
    AuthenticatedSubmissionsIdRoute: AuthenticatedSubmissionsIdRoute,
    AuthenticatedSubmissionsIndexRoute: AuthenticatedSubmissionsIndexRoute,
  }

const AuthenticatedSubmissionsRouteWithChildren =
  AuthenticatedSubmissionsRoute._addFileChildren(
    AuthenticatedSubmissionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedInterestsRoute: typeof AuthenticatedInterestsRoute
  AuthenticatedSubmissionsRoute: typeof AuthenticatedSubmissionsRouteWithChildren
  AuthenticatedSubmitAgentRoute: typeof AuthenticatedSubmitAgentRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedInterestsRoute: AuthenticatedInterestsRoute,
  AuthenticatedSubmissionsRoute: AuthenticatedSubmissionsRouteWithChildren,
  AuthenticatedSubmitAgentRoute: AuthenticatedSubmitAgentRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AgentsRouteChildren {
  AgentsSlugRoute: typeof AgentsSlugRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsSlugRoute: AgentsSlugRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface CommunityRouteChildren {
  CommunityIdRoute: typeof CommunityIdRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityIdRoute: CommunityIdRoute,
  CommunityIndexRoute: CommunityIndexRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface KnowledgeRouteChildren {
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeSlugRoute: KnowledgeSlugRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRouteWithChildren,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRouteWithChildren,
  ContactRoute: ContactRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthorsSlugRoute: AuthorsSlugRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
