-- Durable store for the AI Radar (/radar).
--
-- The page previously fetched ~38 upstream feeds on every cold request. That
-- works, but it puts third-party tail latency on the critical path, throws away
-- everything older than the cache TTL, and leaves no place for a human to
-- intervene. This table makes the ingest a scheduled job and the page a plain
-- database read.
--
-- Moderation model. Radar items are links to third-party publishers, not
-- Melanated In Tech claims, so holding all ~120 items per run for approval
-- would leave the page empty rather than make it safer. Instead:
--   * items publish by default,
--   * items whose text touches the categories docs/daily-content-agent-spec.md
--     marks as mandatory-human-review (legal, financial, compliance, hiring,
--     security, privacy, health, ministry, political) land as 'pending' and
--     stay hidden until an admin approves them,
--   * an admin can reject anything at any time, and a rejected url_hash is
--     never resurfaced by a later ingest.

create table public.radar_items (
  id uuid primary key default gen_random_uuid(),
  -- Hash of the normalized URL. The dedup key across ingests: the same story
  -- reaching us from two feeds collapses to one row.
  url_hash text not null unique,
  url text not null,
  title text not null,
  summary text not null default '',
  -- Specific publisher, e.g. "OpenAI News".
  source text not null,
  source_group text not null
    check (source_group in ('catalog', 'vendors', 'status', 'releases', 'research', 'press', 'community')),
  category text not null
    check (category in ('models', 'agents', 'developer', 'research', 'industry')),
  author text,
  published_at timestamptz not null,
  tags text[] not null default '{}'::text[],
  score integer,
  comments_count integer,
  track text not null check (track in ('build', 'operate', 'secure', 'decide')),
  signal text not null check (signal in ('act', 'watch', 'context')),
  rank double precision not null default 0,
  status text not null default 'published'
    check (status in ('published', 'pending', 'rejected')),
  -- Which rule held this item back, when status is 'pending'.
  hold_reason text,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  review_notes text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (char_length(url) between 8 and 2000),
  check (char_length(title) between 3 and 500),
  check (char_length(summary) <= 2000),
  check (review_notes is null or char_length(review_notes) <= 2000)
);

-- The page's default read: published items, newest first.
create index radar_items_status_published_idx
  on public.radar_items (status, published_at desc);
-- The page's ranked read.
create index radar_items_status_rank_idx
  on public.radar_items (status, rank desc);
-- The admin review queue.
create index radar_items_pending_idx
  on public.radar_items (status, created_at desc)
  where status = 'pending';
create index radar_items_group_idx
  on public.radar_items (source_group, published_at desc);

create trigger radar_items_set_updated_at
  before update on public.radar_items
  for each row execute function public.update_updated_at_column();

-- Append-only audit of every moderation decision.
create table public.radar_item_events (
  id bigint generated by default as identity primary key,
  item_id uuid not null references public.radar_items(id) on delete cascade,
  event_type text not null
    check (event_type in ('ingested', 'held', 'approved', 'rejected', 'reopened')),
  actor_id uuid references auth.users(id) on delete set null,
  from_status text,
  to_status text,
  details jsonb not null default '{}'::jsonb
    check (jsonb_typeof(details) = 'object'),
  created_at timestamptz not null default now()
);

create index radar_item_events_item_created_idx
  on public.radar_item_events (item_id, created_at desc);

-- One row per scheduled ingest. The page reads the newest row to render its
-- "where this came from" strip, so source health survives the move off
-- request-time fetching.
create table public.radar_ingest_runs (
  id uuid primary key default gen_random_uuid(),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  feeds_ok integer not null default 0,
  feeds_total integer not null default 0,
  items_seen integer not null default 0,
  items_new integer not null default 0,
  items_held integer not null default 0,
  -- The AiRadarSourceStatus[] payload for this run.
  source_status jsonb not null default '[]'::jsonb
    check (jsonb_typeof(source_status) = 'array'),
  failure_message text,
  created_at timestamptz not null default now(),
  check (failure_message is null or char_length(failure_message) <= 4000)
);

create index radar_ingest_runs_started_idx
  on public.radar_ingest_runs (started_at desc);

alter table public.radar_items enable row level security;
alter table public.radar_item_events enable row level security;
alter table public.radar_ingest_runs enable row level security;

-- Supabase grants service_role broadly on new tables; revoke and re-grant only
-- what each role needs (same tightening as the content review queue).
revoke all on table public.radar_items from public, anon, authenticated, service_role;
revoke all on table public.radar_item_events from public, anon, authenticated, service_role;
revoke all on table public.radar_ingest_runs from public, anon, authenticated, service_role;
revoke all on sequence public.radar_item_events_id_seq from public, anon, authenticated, service_role;

-- /radar and /radar/feed.xml are public pages, so the browser role may read
-- published items directly. Everything else goes through the service role.
grant select on table public.radar_items to anon, authenticated;
grant select on table public.radar_ingest_runs to anon, authenticated;
grant select, insert, update, delete on table public.radar_items to service_role;
grant select, insert on table public.radar_item_events to service_role;
grant usage, select on sequence public.radar_item_events_id_seq to service_role;
grant select, insert, update on table public.radar_ingest_runs to service_role;

create policy "Published radar items are world readable"
  on public.radar_items for select
  to anon, authenticated
  using (status = 'published');

-- Only the run metadata is public, and it contains no user data.
create policy "Radar ingest runs are world readable"
  on public.radar_ingest_runs for select
  to anon, authenticated
  using (true);

comment on table public.radar_items is
  'Aggregated third-party AI/agent updates for /radar. Populated by the scheduled ingest; items publish by default and held items stay hidden until an admin approves them.';
comment on column public.radar_items.url_hash is
  'Hash of the normalized URL. Unique: the dedup key across feeds and across ingest runs.';
comment on column public.radar_items.status is
  'published = visible on /radar; pending = held by a review rule; rejected = suppressed permanently, never resurfaced by a later ingest.';
comment on table public.radar_item_events is
  'Append-only audit trail for radar ingest and moderation decisions.';
comment on table public.radar_ingest_runs is
  'One row per scheduled ingest, including per-source health for the public transparency strip.';
