-- Server-only review queue for the daily AI education and SEO agent.
-- Packets are drafts for human review; this schema does not publish content.

create table public.content_review_packets (
  id uuid primary key default gen_random_uuid(),
  run_key text not null unique,
  run_date date not null default current_date,
  status text not null default 'requested'
    check (status in ('requested', 'running', 'review', 'approved', 'rejected', 'failed')),
  topic_hint text,
  decision text
    check (decision is null or decision in ('refresh', 'consolidate', 'create', 'reject')),
  cluster text
    check (cluster is null or cluster in ('beginners', 'small-business', 'safety-evaluation', 'churches-nonprofits')),
  primary_query text,
  reader_outcome text,
  primary_url text,
  packet jsonb not null default '{}'::jsonb
    check (jsonb_typeof(packet) = 'object'),
  source_annotations jsonb not null default '[]'::jsonb
    check (jsonb_typeof(source_annotations) = 'array'),
  validation_errors text[] not null default '{}'::text[],
  provider text not null default 'openrouter',
  model_requested text,
  model_used text,
  provider_request_id text,
  prompt_version text not null default 'v1',
  usage jsonb not null default '{}'::jsonb
    check (jsonb_typeof(usage) = 'object'),
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  failure_code text,
  failure_message text,
  requested_by uuid references auth.users(id) on delete set null,
  reviewed_by uuid references auth.users(id) on delete set null,
  review_notes text,
  started_at timestamptz,
  finished_at timestamptz,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (char_length(run_key) between 8 and 200),
  check (topic_hint is null or char_length(topic_hint) <= 500),
  check (review_notes is null or char_length(review_notes) <= 4000),
  check (failure_message is null or char_length(failure_message) <= 4000)
);

create index content_review_packets_status_created_idx
  on public.content_review_packets (status, created_at desc);
create index content_review_packets_run_date_idx
  on public.content_review_packets (run_date desc, created_at desc);

create trigger content_review_packets_set_updated_at
  before update on public.content_review_packets
  for each row execute function public.update_updated_at_column();

create table public.content_review_packet_events (
  id bigint generated by default as identity primary key,
  packet_id uuid not null references public.content_review_packets(id) on delete cascade,
  event_type text not null
    check (event_type in ('requested', 'started', 'generated', 'failed', 'approved', 'rejected', 'reopened')),
  actor_id uuid references auth.users(id) on delete set null,
  from_status text,
  to_status text,
  details jsonb not null default '{}'::jsonb
    check (jsonb_typeof(details) = 'object'),
  created_at timestamptz not null default now()
);

create index content_review_packet_events_packet_created_idx
  on public.content_review_packet_events (packet_id, created_at desc);

alter table public.content_review_packets enable row level security;
alter table public.content_review_packet_events enable row level security;

-- The browser never reads this queue directly. Authenticated admins use
-- server functions that verify the admin role, then use the service role.
revoke all on table public.content_review_packets from public, anon, authenticated;
revoke all on table public.content_review_packet_events from public, anon, authenticated;
revoke all on sequence public.content_review_packet_events_id_seq from public, anon, authenticated;

grant select, insert, update on table public.content_review_packets to service_role;
grant select, insert on table public.content_review_packet_events to service_role;
grant usage, select on sequence public.content_review_packet_events_id_seq to service_role;

comment on table public.content_review_packets is
  'Human-reviewed SEO content briefs generated by the bounded daily content agent. Approval never publishes automatically.';
comment on table public.content_review_packet_events is
  'Append-only audit trail for content-agent generation and review status changes.';
