// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getSupabasePublishableKey, getSupabaseUrl, missingSupabaseMessage } from "./env";

type SupabaseStorage = {
  getItem: (key: string) => string | null | Promise<string | null>;
  setItem: (key: string, value: string) => void | Promise<void>;
  removeItem: (key: string) => void | Promise<void>;
};

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSafeBrowserStorage(): SupabaseStorage | undefined {
  if (typeof window === "undefined") return undefined;

  const memory = new Map<string, string>();

  return {
    getItem(key) {
      try {
        return window.localStorage.getItem(key);
      } catch {
        return memory.get(key) ?? null;
      }
    },
    setItem(key, value) {
      memory.set(key, value);
      try {
        window.localStorage.setItem(key, value);
      } catch {
        // Some embedded/private contexts deny storage access. Keep auth usable in memory.
      }
    },
    removeItem(key) {
      memory.delete(key);
      try {
        window.localStorage.removeItem(key);
      } catch {
        // Storage is best-effort in restricted browser contexts.
      }
    },
  };
}

/**
 * Serializes callbacks in-process. Used when the Web Locks API is unavailable —
 * it cannot coordinate across tabs, but a single tab refreshing its own session
 * is the case that actually matters.
 */
function createMemoryLock() {
  let tail: Promise<unknown> = Promise.resolve();
  return <R>(_name: string, _acquireTimeout: number, fn: () => Promise<R>): Promise<R> => {
    const run = tail.then(fn, fn);
    tail = run.then(
      () => undefined,
      () => undefined,
    );
    return run;
  };
}

const memoryLock = createMemoryLock();

/** True for the storage-partitioning error, as opposed to a failure inside fn. */
function isStorageAccessError(error: unknown): boolean {
  const message = error instanceof Error ? error.message : String(error ?? "");
  return /access to storage|storage is not allowed|securityerror/i.test(message);
}

/**
 * Session lock that degrades instead of throwing.
 *
 * supabase-js coordinates token refresh with navigator.locks. In a
 * storage-partitioned context — an embedded frame, strict privacy settings,
 * blocked third-party storage — that call throws
 *
 *     Access to storage is not allowed from this context.
 *
 * which surfaces as an unhandled rejection out of getSession()/getUser(), and
 * every caller would otherwise need its own .catch (there are 25 of them).
 * Handling it here fixes all of them at once.
 */
async function safeLock<R>(
  name: string,
  acquireTimeout: number,
  fn: () => Promise<R>,
): Promise<R> {
  let locks: { request?: (n: string, f: () => Promise<R>) => Promise<R> } | undefined;
  try {
    locks = (navigator as unknown as { locks?: typeof locks })?.locks;
  } catch {
    locks = undefined; // Touching navigator.locks can itself throw.
  }

  if (typeof locks?.request === "function") {
    try {
      return await locks.request(name, fn);
    } catch (error) {
      // Only retry when the LOCK was refused. If fn threw, rerunning it would
      // double-execute a token refresh.
      if (!isStorageAccessError(error)) throw error;
    }
  }

  return memoryLock(name, acquireTimeout, fn);
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  const SUPABASE_URL = getSupabaseUrl();
  const SUPABASE_PUBLISHABLE_KEY = getSupabasePublishableKey();

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = missingSupabaseMessage(missing);
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: createSafeBrowserStorage(),
      persistSession: true,
      autoRefreshToken: true,
      lock: safeLock,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
